### ISSUE TITLE
使用命令行进行文字语言合成时，报错：“raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file”

### ISSUE THREAD

**Issue by yinghao2016** [PaddlePaddle/PaddleSpeech#2776] opened 2022-12-28 09:13 UTC
具体：
Traceback (most recent call last):
  File "D:\ProgramFiles\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramFiles\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\Scripts\paddlespeech.exe\__main__.py", line 7, in <module>
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\cli\entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\cli\tts\__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\t2s\__init__.py", line 18, in <module>
    from . import frontend
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\t2s\frontend\__init__.py", line 16, in <module>
    from .phonectic import *
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\paddlespeech\t2s\frontend\phonectic.py", line 20, in <module>
    from g2p_en import G2p
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\g2p_en\__init__.py", line 1, in <module>
    from .g2p import G2p
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\g2p_en\g2p.py", line 26, in <module>
    nltk.data.find('corpora/cmudict.zip')
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\nltk\data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\nltk\data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\nltk\compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "E:\PycharmProjects\ConvertWebWithAjax\venv\lib\site-packages\nltk\data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "D:\ProgramFiles\Python38\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\ProgramFiles\Python38\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

下载了nltk也解压到项目根目录，但总是报错，不知道什么原因，求解？

**Comment by yt605155624** [comment] 2022-12-28 09:46
Duplicate of  https://github.com/PaddlePaddle/PaddleSpeech/issues/1925
应该还是没有正常解压到正确的位置, 注意是 ${HOME} 目录

**Comment by yinghao2016** [comment] 2022-12-28 11:26
确实是位置放错了，已经修改过来，多谢！

**Closed as completed** 2022-12-28 12:34 UTC
Labels: Question
