### ISSUE TITLE
windows 下安装报错

### ISSUE THREAD

**Issue by lvsh2012** [PaddlePaddle/PaddleSpeech#2497] opened 2022-10-06 05:26 UTC
Using legacy 'setup.py install' for pyworld, since package 'wheel' is not installed.
Using legacy 'setup.py install' for resampy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for kaldiio, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pattern-singleton, since package 'wheel' is not installed.
Using legacy 'setup.py install' for webrtcvad, since package 'wheel' is not installed.
Using legacy 'setup.py install' for audioread, since package 'wheel' is not installed.
Using legacy 'setup.py install' for distance, since package 'wheel' is not installed.
Installing collected packages: webrtcvad, timer, textgrid, opencc, flatbuffers, distance, braceexpand, appdirs, yacs, win32-setctime, websockets, typeguard, tabulate, regex, pypinyin, pycparser, pybind11, prettytable, praatio, ppft, pox, portalocker, pattern-singleton, onnxruntime, mock, lxml, llvmlite, kaldiio, jsonlines, h5py, g2pM, editdistance, cython, bottleneck, audioread, sacrebleu, pyworld, pypinyin-dict, pooch, pathos, paddlespeech-feat, numba, nltk, loguru, inflect, cffi, soundfile, resampy, g2p-en, nara-wpe, librosa, paddlespeech
  Running setup.py install for webrtcvad ... error
  error: subprocess-exited-with-error

  × Running setup.py install for webrtcvad did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      copying webrtcvad.py -> build\lib.win-amd64-3.8
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> webrtcvad

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: c:\users\l\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip

**Comment by yt605155624** [comment] 2022-10-08 02:25
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195

**Closed as completed** 2022-10-09 02:10 UTC
Labels: Question, Installation
