### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by deyimsf** [PaddlePaddle/PaddleSpeech#2759] opened 2022-12-21 06:01 UTC
## Others
Mac下安装，报下面的错，请问是啥问题?

 paddlespeech tts --input "你好" --output out.wav
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/usr/local/lib/python3.10/site-packages/paddlespeech/cli/__init__.py", line 24, in <module>
    from .vector import VectorExecutor
  File "/usr/local/lib/python3.10/site-packages/paddlespeech/cli/vector/__init__.py", line 14, in <module>
    from .infer import VectorExecutor
  File "/usr/local/lib/python3.10/site-packages/paddlespeech/cli/vector/infer.py", line 25, in <module>
    from paddleaudio.backends import load as load_audio
ImportError: cannot import name 'load' from 'paddleaudio.backends' (/usr/local/lib/python3.10/site-packages/paddleaudio/backends/__init__.py)

**Comment by yt605155624** [comment] 2022-12-21 06:28
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2687

**Closed as completed** 2022-12-26 08:32 UTC
