### ISSUE TITLE
安装成功了以后，运行asr报错，其他功能正常

### ISSUE THREAD

**Issue by cyd1123** [PaddlePaddle/PaddleSpeech#2626] opened 2022-11-04 09:04 UTC
## General Question

(paddle) baker@bakertop:~/PaddleSpeech$ paddlespeech asr --lang zh --input zh.wav
/home/baker/anaconda3/envs/paddle/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
W1104 17:15:45.559458 503005 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W1104 17:15:45.559866 503005 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
TypeError: declarative() got an unexpected keyword argument 'property'

**Comment by cyd1123** [comment] 2022-11-04 09:24
在启用服务时也报下面错误，其他使用命令行进行TTS，声纹提取等操作正常


(paddle) baker@bakertop:~/PaddleSpeech$ paddlespeech_server start --config_file ./demos/speech_server/conf/application.yaml
[2022-11-04 17:20:34,308] [    INFO] - start to init the engine
[2022-11-04 17:20:34,308] [    INFO] - asr : python engine.
W1104 17:20:37.169281 504710 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W1104 17:20:37.169772 504710 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
[2022-11-04 17:20:37,600] [   ERROR] - Failed to start server.
[2022-11-04 17:20:37,600] [   ERROR] - declarative() got an unexpected keyword argument 'property'

**Comment by cyd1123** [comment] 2022-11-04 09:59
对numpy降级后，还是报错

(paddle) baker@bakertop:~/PaddleSpeech$ paddlespeech asr --lang zh --input zh.wav
W1104 17:58:14.451303 514048 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W1104 17:58:14.451769 514048 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
TypeError: declarative() got an unexpected keyword argument 'property'

**Comment by yt605155624** [comment] 2022-11-04 11:22
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2512

建议以后提交 issue 之前先在 issue 区搜一下报错看有没有类似的问题

**Closed as completed** 2022-11-07 02:23 UTC
Labels: Question

**Comment by cyd1123** [comment] 2022-11-07 02:36
> 
非常感谢，已经解决问题
