### ISSUE TITLE
微调TTS时，报错FileNotFoundError: [Errno 2] No such file or directory: '/home/ti/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'

### ISSUE THREAD

**Issue by kq-cheng** [PaddlePaddle/PaddleSpeech#2438] opened 2022-09-22 08:20 UTC
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/ti/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'
我是按照PaddleSpeech/examples/other/tts_finetune/tts3的步骤来的，就是这里报错，不知道为什么，不知道怎么解决

**Comment by yt605155624** [comment] 2022-09-22 08:27
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2437

**Comment by kq-cheng** [comment] 2022-09-23 03:22
解决方案详见 #2437

**Closed as completed** 2022-09-23 03:22 UTC
Labels: Question, T2S
