### ISSUE TITLE
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error

### ISSUE THREAD

**Issue by qiaosir888** [PaddlePaddle/PaddleSpeech#2976] opened 2023-03-01 10:17 UTC
![求助1](https://user-images.githubusercontent.com/86141016/222110119-6bbb6a21-c6d9-4844-918c-28692c976769.png)
![求助2](https://user-images.githubusercontent.com/86141016/222110126-cf111792-114b-4121-a52d-0f395a402755.png)
![求助](https://user-images.githubusercontent.com/86141016/222110130-f154b758-66b3-44a3-837f-800162326264.png)
求助这个是哪里出了问题？文件可以正常生成
麻烦具体告知怎么解决，纯小白一个

**Comment by yt605155624** [comment] 2023-03-01 10:23
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/1925

**Closed as completed** 2023-03-02 07:54 UTC
Labels: Bug, T2S, duplicate
