### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by murat-gunay** [PaddlePaddle/PaddleSpeech#2709] opened 2022-11-30 13:01 UTC
## General Question

Hi,

I couldn't execute text-to-speech module because of an importing error below.
I install all dependencies on my mac m1 ventura. Why may this happen?

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/69839085/204802593-8a3678e9-53a9-4b3b-a86f-f920b72b5432.png">

**Comment by zxcd** [comment] 2022-11-30 13:39
which branch paddlespeech are you using now?

**Comment by yt605155624** [comment] 2022-12-01 02:44
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2687

**Closed as completed** 2022-12-28 11:19 UTC
Labels: Question
