### ISSUE TITLE
!bash run.sh --stage 1 --stop_stage 1 --gpus 0请问使用这个命令运行报错是什么原因

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2469] opened 2022-09-28 01:25 UTC
home/aistudio/PaddleSpeech/examples/aishell/asr1
The standard file /home/aistudio/PaddleSpeech/tools/kaldi/tools/config/common_path.sh is not present, can not using Kaldi!
checkpoint name conformer
using 1 gpus...

-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: /home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py
training_script_args: ['--ngpu', '1', '--seed', '0', '--config', 'conf/conformer.yaml', '--output', 'exp/conformer', '--profiler-options', '', '--benchmark-batch-size', '0', '--benchmark-max-step', '0']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-09-28 09:13:22,403 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-09-28 09:13:22,403 launch_utils.py:641] Change selected_gpus into reletive values. --ips:0 will change into relative_ips:[0] according to your CUDA_VISIBLE_DEVICES:['0']
INFO 2022-09-28 09:13:22,404 launch_utils.py:528] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:34673               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:34673               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-09-28 09:13:22,404 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:3126 idx:0
W0928 09:13:24.236148  3126 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0928 09:13:24.238968  3126 device_context.cc:465] device: 0, cuDNN Version: 8.2.
----------- train.py Arguments -----------
benchmark_batch_size: 0
benchmark_max_step: 0
checkpoint_path: None
conf: None
config: conf/conformer.yaml
decode_cfg: None
dump_config: None
ngpu: 1
nxpu: 0
opts: None
output: exp/conformer
profiler_options: 
seed: 0
-----------------------------------------------------------
accum_grad: 8
batch_bins: 0
batch_count: auto
batch_frames_in: 0
batch_frames_inout: 0
batch_frames_out: 0
batch_size: 32
checkpoint:
  kbest_n: 50
  latest_n: 5
cmvn_file: None
cmvn_file_type: json
decoder: transformer
decoder_conf:
  attention_heads: 4
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 6
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.0
  src_attention_dropout_rate: 0.0
dev_manifest: data/manifest.dev
dist_sampler: False
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.0
  attention_heads: 4
  cnn_module_kernel: 15
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: True
  num_blocks: 12
  output_size: 256
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: True
feat_dim: 80
global_grad_clip: 5.0
log_interval: 100
maxlen_in: 512
maxlen_out: 150
minibatches: 0
model_conf:
  ctc_weight: 0.3
  init_type: kaiming_uniform
  length_normalized_loss: False
  lsm_weight: 0.1
n_epoch: 150
num_encs: 1
num_workers: 2
optim: adam
optim_conf:
  lr: 0.002
  weight_decay: 1e-06
preprocess_config: conf/preprocess.yaml
scheduler: warmuplr
scheduler_conf:
  lr_decay: 1.0
  warmup_steps: 25000
sortagrad: 0
spm_model_prefix: 
stride_ms: 10.0
subsampling_factor: 1
test_manifest: data/manifest.test
train_manifest: data/manifest.train
unit_type: char
vocab_filepath: data/lang_char/vocab.txt
window_ms: 25.0
2022-09-28 09:13:27.162 | INFO     | paddlespeech.s2t.utils.utility:all_version:45 - Deps Module Version:[('python', '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]'),
 ('paddle', '2.2.2'),
 ('paddle_commit', 'b031c389938bfa15e15bb20494c76f86289d77b0'),
 ('soundfile', '0.10.3')]
2022-09-28 09:13:27.164 | INFO     | paddlespeech.s2t.training.trainer:__init__:116 - Rank: 0/1
2022-09-28 09:13:29.897 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:400 - count is auto detected as seq
2022-09-28 09:13:30.132 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:424 - # utts: 120098
2022-09-28 09:13:30.155 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:467 - # minibatches: 3754
2022-09-28 09:13:30.254 | WARNING  | paddlespeech.s2t.io.reader:__init__:76 - [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: LogMelSpectrogramKaldi(fs=16000, n_mels=80, n_frame_shift=10.0, n_frame_length=25.0, dither=0.1))
    1: GlobalCMVN(
            cmvn_path=data/mean_std.json,
            norm_means=True,
            norm_vars=True,)
    2: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    3: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    4: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2022-09-28 09:13:30.970 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:400 - count is auto detected as seq
2022-09-28 09:13:30.993 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:424 - # utts: 14326
2022-09-28 09:13:30.995 | INFO     | paddlespeech.s2t.io.batchfy:make_batchset:467 - # minibatches: 448
2022-09-28 09:13:31.001 | WARNING  | paddlespeech.s2t.io.reader:__init__:76 - [Experimental feature] Some preprocessing will be done for the mini-batch creation using Transformation(
    0: LogMelSpectrogramKaldi(fs=16000, n_mels=80, n_frame_shift=10.0, n_frame_length=25.0, dither=0.1))
    1: GlobalCMVN(
            cmvn_path=data/mean_std.json,
            norm_means=True,
            norm_vars=True,)
    2: TimeWarp(max_time_warp=5, inplace=True, mode=PIL)
    3: FreqMask(F=30, n_mask=2, replace_with_zero=False, inplace=True)
    4: TimeMask(T=40, n_mask=2, replace_with_zero=False, inplace=True))
2022-09-28 09:13:31.002 | INFO     | paddlespeech.s2t.exps.u2.model:setup_dataloader:233 - Setup train/valid Dataloader!
2022-09-28 09:13:31.234 | INFO     | paddlespeech.s2t.modules.embedding:__init__:153 - max len: 5000
Traceback (most recent call last):
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 56, in <module>
    pr.runcall(main, config, args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/cProfile.py", line 121, in runcall
    return func(*args, **kw)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 34, in main
    main_sp(config, args)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 29, in main_sp
    exp.setup()
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 165, in setup
    self.setup_model()
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/exps/u2/model.py", line 255, in setup_model
    model = U2Model.from_config(model_conf)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 953, in from_config
    model = cls(configs)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 861, in __init__
    configs)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 906, in _init_from_config
    input_dim, global_cmvn=global_cmvn, **configs['encoder_conf'])
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/modules/encoder.py", line 468, in __init__
    use_dynamic_left_chunk, max_len)
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/modules/encoder.py", line 130, in __init__
    max_len=max_len), )
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/modules/subsampling.py", line 114, in __init__
    Conv2D(1, odim, 3, 2),
  File "/home/aistudio/PaddleSpeech/paddlespeech/s2t/modules/align.py", line 152, in __init__
    nonlinearity='leaky_relu'))
TypeError: __init__() got an unexpected keyword argument 'negative_slope'
INFO 2022-09-28 09:13:38,447 launch_utils.py:341] terminate all the procs
ERROR 2022-09-28 09:13:38,448 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-09-28 09:13:42,451 launch_utils.py:341] terminate all the procs
INFO 2022-09-28 09:13:42,451 launch.py:311] Local processes completed.

**Comment by yt605155624** [comment] 2022-09-28 02:30
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2401

主要报错是 `TypeError: init() got an unexpected keyword argument 'negative_slope'`
使用 paddle 版本 >= 2.3.1

**Closed as completed** 2022-09-28 06:08 UTC
Labels: Question, S2T
