### ISSUE TITLE
Installation error on MacOS Monterrey

### ISSUE THREAD

**Issue by inglesuniversal** [PaddlePaddle/PaddleSpeech#1975] opened 2022-05-26 17:10 UTC
bash-3.2$ paddlespeech cls --input mySampleAudio.wav 

and I get this error: 

Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/usr/local/lib/python3.9/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/usr/local/lib/python3.9/site-packages/paddlespeech/cli/base_commands.py", line 17, in <module>
    from .utils import cli_register
  File "/usr/local/lib/python3.9/site-packages/paddlespeech/cli/utils.py", line 26, in <module>
    import paddle
  File "/usr/local/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "/usr/local/lib/python3.9/site-packages/paddle/fluid/proto/framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Any idea what is causing it?

Thanks

**Comment by yt605155624** [comment] 2022-05-26 17:10
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/1970

it's caused by the new release of protobuf，which break paddlepaddle

you should 
```bash
pip install protobuf==3.20.1
```

**Closed as completed** 2022-05-30 02:34 UTC
