### ISSUE TITLE
执行语音转文字报错

### ISSUE THREAD

**Issue by MemoryF** [PaddlePaddle/PaddleSpeech#2766] opened 2022-12-27 01:47 UTC
## General Question

Traceback (most recent call last):
  File "/tmp/dataspell_projects/Users/fanwenjie/Documents/project/paddle241/demo8.py", line 1, in <module>
    from paddlespeech.cli.asr.infer import ASRExecutor
  File "/root/anaconda3/envs/paddle241/lib/python3.10/site-packages/paddlespeech/cli/__init__.py", line 24, in <module>
    from .vector import VectorExecutor
  File "/root/anaconda3/envs/paddle241/lib/python3.10/site-packages/paddlespeech/cli/vector/__init__.py", line 14, in <module>
    from .infer import VectorExecutor
  File "/root/anaconda3/envs/paddle241/lib/python3.10/site-packages/paddlespeech/cli/vector/infer.py", line 25, in <module>
    from paddleaudio.backends import load as load_audio
ImportError: cannot import name 'load' from 'paddleaudio.backends' (/root/anaconda3/envs/paddle241/lib/python3.10/site-packages/paddleaudio/backends/__init__.py)

版本
conda 22.11.1
paddle2onnx               1.0.5                    pypi_0    pypi
paddleaudio               1.0.2                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.4.7                    pypi_0    pypi
paddleocr                 2.6.1.2                  pypi_0    pypi
paddlepaddle-gpu          2.4.1.post117            pypi_0    pypi
paddlespeech              1.0.1                    pypi_0    pypi
paddlespeech-feat         0.1.0                    pypi_0    pypi

系统 ubantu 20.04

执行的代码：
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
result = asr(audio_file="/data/paddle241/zh.wav")
print(result)

**Comment by yt605155624** [comment] 2022-12-27 02:10
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2687

**Closed as completed** 2022-12-28 02:55 UTC
Labels: Question, S2T
