### ISSUE TITLE
[S2T] FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by MoYinYu** [PaddlePaddle/PaddleSpeech#2503] opened 2022-10-08 07:47 UTC
您好，我按安装教程拉取官网dockers安装。[develop-gpu-cuda11.2-cudnn8-latest]
之后按example/aishell/sr1 的教程，bash run.sh --stage 1 --stop_stage 1时，出现以下错误：
TypeError: __init__() got an unexpected keyword argument 'negative_slope'
参考其他issues，将paddle2.3.0-gpu升级为2.3.1-gpu，主机环境为A100、CUDA Version: 11.2，结果出现以下错误：
。。。
2022-10-08 07:16:43.986 | INFO     | paddlespeech.s2t.training.optimizer:from_args:120 - <Optimizer paddle.optimizer.adam.Adam> LR: WarmupLR(warmup_steps=25000, lr=0.002, last_epoch=0)
2022-10-08 07:16:43.986 | INFO     | paddlespeech.s2t.exps.u2.model:setup_model:304 - Setup optimizer/lr_scheduler!
2022-10-08 07:16:43.987 | INFO     | paddlespeech.s2t.training.trainer:resume_or_scratch:225 - Init from scratch!
2022-10-08 07:16:44.464 | INFO     | paddlespeech.s2t.utils.checkpoint:_save_parameters:286 - Saved model to exp/conformer/checkpoints/init.pdparams
2022-10-08 07:16:44.466 | INFO     | paddlespeech.s2t.utils.checkpoint:_save_parameters:292 - Saved optimzier state to exp/conformer/checkpoints/init.pdopt
2022-10-08 07:16:44.466 | INFO     | paddlespeech.s2t.exps.u2.model:do_train:160 - Train Total Examples: 30025
/home/PaddleSpeech/paddlespeech/audio/transform/spec_augment.py:48: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  Image.BICUBIC)
/home/PaddleSpeech/paddlespeech/audio/transform/spec_augment.py:50: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  Image.BICUBIC)
/home/PaddleSpeech/paddlespeech/audio/transform/spec_augment.py:48: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  Image.BICUBIC)
/home/PaddleSpeech/paddlespeech/audio/transform/spec_augment.py:50: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  Image.BICUBIC)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   void paddle::imperative::Tracer::TraceOpImpl<paddle::imperative::VarBase>(std::string const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::AttributeMap&, phi::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&, paddle::framework::AttributeMap*, bool)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   void phi::ArangeKernel<long, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor*)

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1665213404 (unix time) try "date -d @1665213404" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7ff9b1daf5f3) received by PID 1460 (TID 0x7ffa0b562740) from PID 18446744072398501363 ***]

INFO 2022-10-08 07:16:59,575 launch_utils.py:343] terminate all the procs
INFO 2022-10-08 07:16:59,575 launch_utils.py:343] terminate all the procs
ERROR 2022-10-08 07:16:59,575 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-10-08 07:16:59,575 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-10-08 07:17:03,579 launch_utils.py:343] terminate all the procs
INFO 2022-10-08 07:17:03,579 launch_utils.py:343] terminate all the procs
INFO 2022-10-08 07:17:03,579 launch.py:402] Local processes completed.
INFO 2022-10-08 07:17:03,579 launch.py:402] Local processes completed.

**Comment by yt605155624** [comment] 2022-10-08 08:05
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2401

**Comment by MoYinYu** [comment] 2022-10-09 07:18
估计是paddle安装的版本没对上的原因，到官网下载一个paddlepaddle_gpu-2.3.2.post112-cp37-cp37m-linux_x86_64.whl，用这个覆盖掉之前的paddlepaddle_gpu-2.3.1-cp37-cp37m-manylinux1_x86_64.whl，目前可以正常使用单核gpu训练。

**Closed as completed** 2022-10-09 07:19 UTC
Labels: Bug, S2T
