### ISSUE TITLE
arm架构下部署paddlespeech

### ISSUE THREAD

**Issue by cater555** [PaddlePaddle/PaddleSpeech#2563] opened 2022-10-21 00:18 UTC
我尝试在jetson nano上部署paddlespeech , 但是paddlepaddle的最高版本是2.3.2。部署的过程中发现paddlespeech_ctcdecoders没有arm架构的包。部署之后运行speech_web/speech_server报错

File "/usr/local/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 611, in U2BaseModel
    @jit.to_static(property=True)
TypeError: declarative() got an unexpected keyword argument 'property'

环境：python 3.7，paddlepaddle2.3.2

请问我该如何解决出现的问题？

**Comment by yt605155624** [comment] 2022-10-21 00:34
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2512

如果没有 arm 的 paddle2.4.0rc 可以使用 1.2.0 版本的 paddlespeech

ctcdecoders 尝试自己编译 https://github.com/PaddlePaddle/PaddleSpeech/discussions/2148

**Comment by cater555** [comment] 2022-10-21 00:48
ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from paddlespeech[develop]) (from versions: none)

请问这个有什么影响？

**Comment by yt605155624** [comment] 2022-10-21 02:42
see https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install.md

**Closed as completed** 2022-10-24 02:36 UTC
Labels: Question
