### ISSUE TITLE
voxceleb2下载不了了？ 

### ISSUE THREAD

**Issue by JJun-Guo** [PaddlePaddle/PaddleSpeech#2393] opened 2022-09-16 09:25 UTC
--2022-09-16 17:21:19--  https://www.robots.ox.ac.uk/~vgg/data/voxceleb/data//vox2_dev_aac_partaa
Resolving www.robots.ox.ac.uk (www.robots.ox.ac.uk)... 129.67.94.2
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-16 17:21:19 ERROR 404: Not Found.

**Comment by yt605155624** [comment] 2022-09-16 10:17
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2161

**Closed as completed** 2022-09-19 02:22 UTC
Labels: Question

**Comment by will-wiki** [comment] 2022-09-28 03:09
@JJ-Guo1996 同样的报错，voxceleb1能下载，但是voxceleb2下载不了显示404
