### ISSUE TITLE
[OpenCL] pwg_baker_static_0.4 fail

### ISSUE THREAD

**Issue by yyqwert4** [PaddlePaddle/PaddleSpeech#2534] opened 2022-10-17 03:07 UTC
标题：[OpenCL] pwg_baker_static_0.4 fail
    版本、预测库信息：
       1）Paddle Lite 版本：branch develop
       2）Host 环境：Ubuntu 22.04
       3）运行设备环境：X86
       4）预测后端信息：OpenCL AMD Radeon RX 6900 XT
    预测信息
       1）预测 API：API：C++
       2）预测选项信息：benchmark_bin，

cmd="gdb -args ./build.lite.linux.x86.gcc.opencl/lite/api/tools/benchmark/benchmark_bin --model_file=./models/pwg_baker_static_0.4/pwgan_csmsc.pdmodel --param_file=./models/pwg_baker_static_0.4/pwgan_csmsc.pdiparams -input_shape=1,80 --warmup=10 --repeats=20 --backend=opencl,x86 --gpu_precision=fp32"

-Model link
https://paddlespeech.bj.bcebos.com/Parakeet/released_models/pwgan/pwg_baker_static_0.4.zip

======= Opt Info =======
Load paddle model from ./models/pwg_baker_static_0.4/pwgan_csmsc.pdmodel and ./models/pwg_baker_static_0.4/pwgan_csmsc.pdiparams
Save optimized model to ./models/pwg_baker_static_0.4/opt.nb
I1017 10:41:20.336551 3691052 paddle_api.cc:50] need to check fp16 valid:0
I1017 10:41:20.336556 3691052 paddle_api.cc:57] Found opencl library:1
I1017 10:41:20.336557 3691052 paddle_api.cc:63] dlsym_success:1
I1017 10:41:20.336560 3691052 cl_runtime.h:93] need to check fp16 valid:0
I1017 10:41:20.336561 3691052 paddle_api.cc:70] opencl_valid:1
I1017 10:41:20.336565 3691052 paddle_api.cc:323] opencl binary path and file name:/paddle_lite_opencl_kernel.bin
I1017 10:41:20.336566 3691052 paddle_api.cc:50] need to check fp16 valid:0
I1017 10:41:20.336567 3691052 paddle_api.cc:57] Found opencl library:1
I1017 10:41:20.336568 3691052 paddle_api.cc:63] dlsym_success:1
I1017 10:41:20.336570 3691052 cl_runtime.h:93] need to check fp16 valid:0
I1017 10:41:20.336571 3691052 paddle_api.cc:70] opencl_valid:1
I1017 10:41:20.336578 3691052 cl_runtime.cc:863] tuned_file:/paddle_lite_opencl_tuned.params
W1017 10:41:20.336585 3691052 cl_runtime.cc:872] Not found tuned file:/paddle_lite_opencl_tuned.params
[New Thread 0x7ffff751f640 (LWP 3691100)]
I1017 10:41:20.345726 3691052 paddle_api.cc:341] set opencl_tune_mode: CL_TUNE_NORMAL, lws_repeats:4
I1017 10:41:20.345738 3691052 paddle_api.cc:344] tuned file path & name:/paddle_lite_opencl_tuned.params
I1017 10:41:20.345741 3691052 paddle_api.cc:50] need to check fp16 valid:0
I1017 10:41:20.345742 3691052 paddle_api.cc:57] Found opencl library:1
I1017 10:41:20.345743 3691052 paddle_api.cc:63] dlsym_success:1
I1017 10:41:20.345744 3691052 cl_runtime.h:93] need to check fp16 valid:0
I1017 10:41:20.345747 3691052 paddle_api.cc:70] opencl_valid:1
I1017 10:41:20.345748 3691052 paddle_api.cc:356] set opencl precision: CL_PRECISION_FP32
[Thread 0x7ffff75d0640 (LWP 3691057) exited]
I1017 10:41:20.388281 3691052 cl_runtime.h:93] need to check fp16 valid:0
W1017 10:41:20.388857 3691052 cl_runtime.cc:220] There is no precompiled OpenCL binary[/paddle_lite_opencl_kernel.bin] in the given OpenCL binary path. Also please make sure the storage directory exist and you have Write&Read permission. Jump to build program from source.
I1017 10:41:20.474515 3691052 elementwise_image_compute.cc:100] with y->persistable
I1017 10:41:20.522027 3691052 elementwise_image_compute.cc:100] with y->persistable

Thread 1 "benchmark_bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff7663a6e in clEnqueueCopyBuffer () from /opt/rocm-5.2.3/lib/libamdocl64.so

(gdb) bt
#0 0x00007ffff7663a6e in clEnqueueCopyBuffer () from /opt/rocm-5.2.3/lib/libamdocl64.so
https://github.com/PaddlePaddle/Paddle-Lite/issues/1 0x00007ffff7fb3f42 in clEnqueueCopyBuffer (command_queue=0x555559946820, src_buffer=0xbdc131e43daa7a32, dst_buffer=0x555559fc3000, src_offset=0,
dst_offset=0, cb=128000, num_events_in_wait_list=0, event_wait_list=0x0, event=0x0)
at /home/qingchuan/work/ROCm/ROCm-OpenCL-Runtime/khronos/icd/loader/icd_dispatch.c:975
https://github.com/PaddlePaddle/Paddle-Lite/issues/2 0x00005555567d22fb in clEnqueueCopyBuffer (command_queue=0x555559946820, src_buffer=0xbdc131e43daa7a32, dst_buffer=0x555559fc3000, src_offset=0,
dst_offset=0, size=128000, num_events_in_wait_list=0, event_wait_list=0x0, event=0x0)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/backends/opencl/cl_wrapper.cc:759
https://github.com/PaddlePaddle/Paddle-Lite/issues/3 0x0000555557564b23 in cl::CommandQueue::enqueueCopyBuffer (this=0x7fffffffd608, src=..., dst=..., src_offset=0, dst_offset=0, size=128000,
events=0x0, event=0x0) at /home/yaoyao/work/gitlab/fortest/paddle-lite/third-party/opencl/include/CL/cl2.hpp:7090
https://github.com/PaddlePaddle/Paddle-Lite/issues/4 0x0000555557562c6a in paddle::lite::TargetWrapper<(paddle::lite_api::TargetType)5, cl::CommandQueue, cl::Event>::MemcpySync (dst=0x555559696690,
src=0x555558eccfc0, size=128000, dir=paddle::lite::IoDirection::DtoD)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/backends/opencl/target_wrapper.cc:250
https://github.com/PaddlePaddle/Paddle-Lite/issues/5 0x00005555569a05a7 in paddle::lite::kernels::opencl::CopyFromDeviceToDeviceSync (target=0x555559696690, source=0x555558eccfc0, size=128000)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/kernels/opencl/io_copy_buffer_compute.cc:66
https://github.com/PaddlePaddle/Paddle-Lite/issues/6 0x000055555697e85d in paddle::lite::kernels::opencl::SqueezeUnsqueezeCompute::Run (this=0x55555925bc20)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/kernels/opencl/squeeze_unsqueeze_buffer_compute.cc:63
https://github.com/PaddlePaddle/Paddle-Lite/issues/7 0x00005555567f8a08 in paddle::lite::KernelBase::Launch (this=0x55555925bc20) at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/core/kernel.h:116
https://github.com/PaddlePaddle/Paddle-Lite/issues/8 0x00005555578e1145 in paddle::lite::Instruction::Run (this=0x555558b93130) at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/core/program.cc:843
https://github.com/PaddlePaddle/Paddle-Lite/issues/9 0x00005555578df449 in paddle::lite::RuntimeProgram::Run (this=0x5555591fd3a0)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/core/program.cc:643
https://github.com/PaddlePaddle/Paddle-Lite/issues/10 0x000055555688577a in paddle::lite::LightPredictor::Run (this=0x55555902e9b0)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/light_api.h:71
https://github.com/PaddlePaddle/Paddle-Lite/issues/11 0x00005555568820a8 in paddle::lite::LightPredictorImpl::Run (this=0x555559286ec0)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/light_api_impl.cc:139
https://github.com/PaddlePaddle/Paddle-Lite/issues/12 0x00005555566da0e4 in paddle::lite_api::RunImpl (predictor=std::shared_ptrpaddle::lite_api::PaddlePredictor (use count 2, weak count 0) = {...},
perf_data=0x7fffffffdbb0) at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/tools/benchmark/benchmark.cc:82
https://github.com/PaddlePaddle/Paddle-Lite/issues/13 0x00005555566da677 in paddle::lite_api::Run (model_file="./models/pwg_baker_static_0.4/opt.nb",
input_shapes=std::vector of length 1, capacity 1 = {...}) at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/tools/benchmark/benchmark.cc:193
https://github.com/PaddlePaddle/Paddle-Lite/issues/14 0x00005555566d9e7f in paddle::lite_api::Benchmark (argc=1, argv=0x7fffffffe230)
at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/tools/benchmark/benchmark.cc:60
https://github.com/PaddlePaddle/Paddle-Lite/issues/15 0x00005555566d9d87 in main (argc=8, argv=0x7fffffffe1f8) at /home/yaoyao/work/gitlab/fortest/paddle-lite/lite/api/tools/benchmark/benchmark.cc:36
(gdb)

**Comment by yt605155624** [comment] 2022-10-18 03:21
Duplicate of https://github.com/PaddlePaddle/Paddle-Lite/issues/9556

**Closed as completed** 2023-03-02 09:23 UTC
Labels: Bug, T2S
