### ISSUE TITLE
TypeError: declarative() got an unexpected keyword argument 'property'

### ISSUE THREAD

**Issue by snailyang** [PaddlePaddle/PaddleSpeech#2619] opened 2022-11-03 02:38 UTC
## General Question

执行
 paddlespeech asr --lang zh --input zh.wav
报错
/home/PaddleSpeech/tools/venv/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
W1102 22:26:24.607908 24372 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 10.2
W1102 22:26:24.610229 24372 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
TypeError: declarative() got an unexpected keyword argument 'property'

环境：

paddlepaddle = 2.4rc
python= 3.7
linux 7.9

(/home/PaddleSpeech/tools/venv) [root@MiWiFi-R3D-srv tts3]# nvidia-smi 
Wed Nov  2 22:37:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 31%   34C    P0    39W / 215W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by yt605155624** [comment] 2022-11-03 03:07
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2512

**Closed as completed** 2022-11-03 12:15 UTC
Labels: Question
