### ISSUE TITLE
语音识别报错

### ISSUE THREAD

**Issue by ChayYue** [PaddlePaddle/PaddleSpeech#2567] opened 2022-10-21 08:25 UTC
paddlespeech安装完成后快速测试语音识别报错：（执行语音合成命令正常响应）
执行：paddlespeech asr --lang zh --input zh.wav
报错：/anaconda3/envs/paddlepaddle39/lib/python3.9/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
TypeError: declarative() got an unexpected keyword argument 'property'(paddlepaddle39)

本地环境：ubuntu18.04+conda创建虚拟环境（python3.9）

安装参考：https://github.com/PaddlePaddle/PaddleSpeech
                  https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md

**Comment by yt605155624** [comment] 2022-10-21 08:34
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2512

**Comment by JYCcx** [comment] 2022-10-23 10:58
aistudio 运行transfomer识别时，出现没有包的情况，paddlespeech更新到最新版也这样
![1666522652423](https://user-images.githubusercontent.com/116490558/197388281-222fc8c1-333d-47f5-921f-e34f4247eb4f.png)

**Comment by yt605155624** [comment] 2022-10-24 06:47
@JYCcx 是 paddlespeech 不兼容升级导致的，AISTUDIO 教程这两天会修复，可以先尝试安装旧版本的 paddlespeech, 如 paddlespeech 0.1.0

**Closed as completed** 2022-10-27 03:12 UTC
Labels: S2T
